[build]
  publish = "."          # indica que os arquivos públicos estão na raiz
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild" # otimiza funções serverless

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
